//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritabanıKatman
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneOtomasyonSistemiDBEntities : DbContext
    {
        public KutuphaneOtomasyonSistemiDBEntities()
            : base("name=KutuphaneOtomasyonSistemiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Atama> tbl_Atama { get; set; }
        public virtual DbSet<tbl_Calisan> tbl_Calisan { get; set; }
        public virtual DbSet<tbl_Departman> tbl_Departman { get; set; }
        public virtual DbSet<tbl_Kitap> tbl_Kitap { get; set; }
        public virtual DbSet<tbl_KitapCeza> tbl_KitapCeza { get; set; }
        public virtual DbSet<tbl_KitapDonus> tbl_KitapDonus { get; set; }
        public virtual DbSet<tbl_KitapTipi> tbl_KitapTipi { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_KullaniciTipi> tbl_KullaniciTipi { get; set; }
        public virtual DbSet<tbl_Satici> tbl_Satici { get; set; }
        public virtual DbSet<tbl_SatinAlim> tbl_SatinAlim { get; set; }
        public virtual DbSet<tbl_SatinAlimDetay> tbl_SatinAlimDetay { get; set; }
        public virtual DbSet<tbl_SatinAlinanDetay> tbl_SatinAlinanDetay { get; set; }
        public virtual DbSet<tbl_VerilenKitap> tbl_VerilenKitap { get; set; }
    }
}
