//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritabanıKatman
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SatinAlimDetay
    {
        public int id_SatinAlimDetay { get; set; }
        public int id_Kitap { get; set; }
        public int id_SatinAlim { get; set; }
        public int adet { get; set; }
        public double birimFiyat { get; set; }
    
        public virtual tbl_Kitap tbl_Kitap { get; set; }
        public virtual tbl_SatinAlim tbl_SatinAlim { get; set; }
    }
}
