//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritabanıKatman
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Atama
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Atama()
        {
            this.tbl_Calisan = new HashSet<tbl_Calisan>();
        }
    
        public int id_Atama { get; set; }
        [Required(ErrorMessage = "Lütfen atama ismi girin")]
        public string isim { get; set; }
        public int id_Kullanici { get; set; }
        [Required(ErrorMessage = "Lütfen atama ölçüsü girin")]
        public string olcu { get; set; }
    
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Calisan> tbl_Calisan { get; set; }
    }
}
