//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritabanıKatman
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Satici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Satici()
        {
            this.tbl_SatinAlim = new HashSet<tbl_SatinAlim>();
        }
    
        public int id_Satici { get; set; }
        [Required(ErrorMessage = "Lütfen satıcı adı girin")]
        public string adi { get; set; }
        public int id_Kullanici { get; set; }
        [Required(ErrorMessage = "Lütfen iletişim numarası girin")]
        public int iletisimNo { get; set; }
        [Required(ErrorMessage = "Lütfen email girin")]
        public string email { get; set; }
        public string aciklama { get; set; }
    
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SatinAlim> tbl_SatinAlim { get; set; }
    }
}
