//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritabanıKatman
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kullanici()
        {
            this.tbl_Atama = new HashSet<tbl_Atama>();
            this.tbl_Departman = new HashSet<tbl_Departman>();
            this.tbl_Kitap = new HashSet<tbl_Kitap>();
            this.tbl_KitapDonus = new HashSet<tbl_KitapDonus>();
            this.tbl_KitapDonus1 = new HashSet<tbl_KitapDonus>();
            this.tbl_Satici = new HashSet<tbl_Satici>();
            this.tbl_SatinAlim = new HashSet<tbl_SatinAlim>();
            this.tbl_VerilenKitap = new HashSet<tbl_VerilenKitap>();
            this.tbl_VerilenKitap1 = new HashSet<tbl_VerilenKitap>();
        }
    
        public int id_Kullanici { get; set; }
        [Required(ErrorMessage = "Lütfen kullanıcı tipi girin")]
        public int id_KullaniciTipi { get; set; }
        [Required(ErrorMessage = "Lütfen kullanıcı adı girin")]
        public string kullaniciAdi { get; set; }
        [Required(ErrorMessage = "Lütfen şifre girin")]
        public string sifre { get; set; }
        [Required(ErrorMessage = "Lütfen çalışan seçin")]
        public int id_Calisan { get; set; }
        [Display(Name="Durum")]
        public bool aktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Atama> tbl_Atama { get; set; }
        public virtual tbl_Calisan tbl_Calisan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Departman> tbl_Departman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Kitap> tbl_Kitap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KitapDonus> tbl_KitapDonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KitapDonus> tbl_KitapDonus1 { get; set; }
        public virtual tbl_KullaniciTipi tbl_KullaniciTipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Satici> tbl_Satici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SatinAlim> tbl_SatinAlim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VerilenKitap> tbl_VerilenKitap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VerilenKitap> tbl_VerilenKitap1 { get; set; }
    }
}
