//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritabanıKatman
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_KitapTipi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KitapTipi()
        {
            this.tbl_Kitap = new HashSet<tbl_Kitap>();
        }
    
        public int id_KitapTipi { get; set; }
        [Required(ErrorMessage = "Lütfen kitap tipi girin")]
        public string isim { get; set; }
        public int id_Kullanici { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Kitap> tbl_Kitap { get; set; }
    }
}
