//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritabanıKatman
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_SatinAlim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SatinAlim()
        {
            this.tbl_SatinAlimDetay = new HashSet<tbl_SatinAlimDetay>();
        }

        public int id_SatinAlim { get; set; }
        [Required(ErrorMessage = "Lütfen satın alım tarihi seçin")]
        [DataType(DataType.Date)]
        public System.DateTime satinAlimTarihi { get; set; }
        public int id_Kullanici { get; set; }
        [Required(ErrorMessage = "Lütfen satın alım miktarı girin")]
        public double satinAlimMiktari { get; set; }
        [Required(ErrorMessage = "Lütfen satıcı seçin")]
        public int id_Satici { get; set; }
    
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        public virtual tbl_Satici tbl_Satici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SatinAlimDetay> tbl_SatinAlimDetay { get; set; }
    }
}
