//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritabanıKatman
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kitap()
        {
            this.tbl_SatinAlimDetay = new HashSet<tbl_SatinAlimDetay>();
            this.tbl_VerilenKitap = new HashSet<tbl_VerilenKitap>();
            this.tbl_VerilenKitap1 = new HashSet<tbl_VerilenKitap>();
            this.tbl_VerilenKitap2 = new HashSet<tbl_VerilenKitap>();
            this.tbl_SatinAlinanDetay = new HashSet<tbl_SatinAlinanDetay>();
        }
    
        public int id_Kitap { get; set; }
        public int id_Kullanici { get; set; }
        [Required(ErrorMessage = "Lütfen departman seçin")]
        public int id_Departman { get; set; }
        [Required(ErrorMessage = "Lütfen kitap tipi seçin")]
        public int id_KitapTipi { get; set; }
        [Required(ErrorMessage = "Lütfen kitap başlığı girin")]
        public string kitapBaslik { get; set; }
        [Required(ErrorMessage = "Lütfen kısa açıklama girin")]
        [DataType(DataType.MultilineText)]
        public string kisaAciklama { get; set; }
        [Required(ErrorMessage = "Lütfen yazar girin")]
        public string yazar { get; set; }
        [Required(ErrorMessage = "Lütfen kitap adı girin")]
        public string kitapAdi { get; set; }
        [Required(ErrorMessage = "Lütfen edisyon girin")]
        public double edisyon { get; set; }
        [Required(ErrorMessage = "Lütfen toplam kopya girin")]
        public int toplamKopya { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage ="Lütfen kayıt tarihi girin")]
        public System.DateTime kayitTarihi { get; set; }
        [Required(ErrorMessage = "Lütfen fiyat girin")]
        [DataType(DataType.Currency)]
        public double fiyat { get; set; }
        [DataType(DataType.MultilineText)]
        public string aciklama { get; set; }
    
        public virtual tbl_Departman tbl_Departman { get; set; }
        public virtual tbl_KitapTipi tbl_KitapTipi { get; set; }
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SatinAlimDetay> tbl_SatinAlimDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VerilenKitap> tbl_VerilenKitap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VerilenKitap> tbl_VerilenKitap1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VerilenKitap> tbl_VerilenKitap2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SatinAlinanDetay> tbl_SatinAlinanDetay { get; set; }
    }
}
