//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritabanıKatman
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_SatinAlinanDetay
    {
        public int id_SatinAlinan { get; set; }
        [Required(ErrorMessage  = "Kitap Seçiniz")]
        public int id_Kitap { get; set; }
        [Required(ErrorMessage = "Miktar giriniz")]
        public int adet { get; set; }
        [Required(ErrorMessage = "Birim fiyat giriniz")]
        public double birimFiyat { get; set; }
    
        public virtual tbl_Kitap tbl_Kitap { get; set; }
    }
}
