//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritabanıKatman
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Calisan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Calisan()
        {
            this.tbl_KitapCeza = new HashSet<tbl_KitapCeza>();
            this.tbl_KitapDonus = new HashSet<tbl_KitapDonus>();
            this.tbl_Kullanici = new HashSet<tbl_Kullanici>();
            this.tbl_VerilenKitap = new HashSet<tbl_VerilenKitap>();
        }
    
        public int id_Calisan { get; set; }
        public int id_Kullanici { get; set; }
        [Required(ErrorMessage = "Lütfen ad ve soyad giriniz")]
        public string tamAdi { get; set; }
        [Required(ErrorMessage = "Lütfen baba adı girin")]
        public string babaAdi { get; set; }
        [Required(ErrorMessage = "Lütfen iletişim no girin")]
        public string iletisimNo { get; set; }
        [Required(ErrorMessage = "Lütfen email girin")]
        public string email { get; set; }
        [Required(ErrorMessage = "Lütfen adres girin")]
        public string adres { get; set; }
        [Required(ErrorMessage = "Lütfen atama seçin")]
        public int id_Atama { get; set; }
        [Required(ErrorMessage = "Lütfen departman seçin")]
        public int id_Departman { get; set; }
        [Display(Name="Durum")]
        public bool aktifMi { get; set; }
        public string aciklama { get; set; }
    
        public virtual tbl_Atama tbl_Atama { get; set; }
        public virtual tbl_Departman tbl_Departman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KitapCeza> tbl_KitapCeza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KitapDonus> tbl_KitapDonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Kullanici> tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VerilenKitap> tbl_VerilenKitap { get; set; }
    }
}
